import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Big Brain",
  description: "Generated by create next app",
  icons: ["/favicon.ico?v=4"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <div
            className={cn(
              inter.className,
              "min-w-full antialiased min-h-screen pt-16"
            )}
          >
            <Providers>
              <Navbar />
              {children}
              <Toaster />
            </Providers>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
